### ISSUE TITLE
asicmanifest.xml sould be called ASiCManifest.xml

### ISSUE THREAD

**Issue by stefan2904** [phax/ph-asic#3]
In multiple locations, `ph-asic` creates the ASiC manifest file named `META-INF/asicmanifest.xml`, while many libraries expect it to be called `META-INF/ASiCManifest.xml`.

Is there a reason this is done that way, or is this a bug?

---

```
./com/helger/asic/CadesAsicWriter.java:    m_aAsicOutputStream.writeZipEntry ("META-INF/asicmanifest.xml", aManifestBytes);
./com/helger/asic/AsicUtils.java:  public static final Pattern PATTERN_CADES_MANIFEST = Pattern.compile ("META-INF/asicmanifest(.*)\\.xml",
./com/helger/asic/AsicUtils.java:                aAOS.putNextEntry (new ZipEntry ("META-INF/asicmanifest" + nManifestCounter + ".xml"));
```

According to [ETSI TS 102 918 V1.3.1](https://portal.etsi.org/webapp/workprogram/Report_WorkItem.asp?WKI_ID=42455): 

![Selection_999(478)](https://user-images.githubusercontent.com/527767/69165502-fd392c00-0af1-11ea-91af-3449057a6733.png)

[DSS also assumes](https://github.com/esig/dss/search?l=Java&q=asicmanifest.xml) that the file is called `ASiCManifest.xml` and cannot load a container created using `ph-asic` (`The manifest file is absent!` etc.).

---

This is also a issue in the repo from which you forked: https://github.com/difi/asic/issues/7

**Comment by phax** [comment]
Thanks for the comment. Highly appreciated. Will be fixed ASAP.

**Comment by phax** [comment]
Fixed in v1.4.1

**Comment by stefan2904** [comment]
Hey Philip, thanks a lot for the fast fix! Cheers from Graz.

**Comment by phax** [comment]
Hey Stefan - yw. If you find more issues, just let me know. I know others (Greece) are also digging into the DSS inconsistencies atm.
Xades stuff will btw. be deprecated and most likely removed...

**Comment by phax** [comment]
Btw. do you need a new release or is it just "for my information"?

**Comment by stefan2904** [comment]
> I know others (Greece) are also digging into the DSS inconsistencies atm.

University of Piraeus? ;-)


> Btw. do you need a new release or is it just "for my information"?

We don't use ph-asic directly, but our project partners do to create the input to our software (which uses DSS & DD4J). So I assume they would be happy about a release, but I don't know how urgent.


> Xades stuff will btw. be deprecated and most likely removed...

Can I ask why? Because Peppol does not use it, and pd-asic is mostly used in the Peppol world?

(DD4J does not support CAdES based ASiC containers, this is why we integrated DSS directly to support it. It seems DSS it the only way to support both CAdES and XAdES based containers now ...)

**Comment by phax** [comment]
* Yes, Unipi
* thanks for the info
* Ad Xades - we use it only in TOOP atm - and there we're happy with CAdES - and the XAdES implementation is simply crappy. But I'm always happy with PRs ;-)
