### ISSUE TITLE
manifest.xml file in the META-INF folder [Minor]

### ISSUE THREAD

**Issue by kdoul** [phax/ph-asic#7]
ph-asic adds this in the ASiCs it produces but this is not included in the ETSI standard.
This could cause some issues with other libraries. For example, the DSS library shows a warning that this file is not supported:
`Unsupported files : [Name: META-INF/manifest.xml / text/xml / null]`

**Comment by phax** [comment]
This seems to be from
```
OASIS OpenDocument v1.0
  OASIS standard, 1 May 2005
  Relax-NG Manifest Schema
```

**Comment by phax** [comment]
With the new API `AsicWriterFactory.newContainer` you have the possibility to add a parameter to disable creation of the OASIS manifest. That should do the trick.
